### ISSUE TITLE
problem programming the application with SD s110 v7 alpha 3

### ISSUE THREAD

**Issue by ahadjeres** [hlnd/nrf51-pure-gcc-setup#9]
Hi 
i am not able write my application after I flashed the SD. I am using Jlinker lite (the one that comes with the Dev kit) and the scripts from the nrf pure gcc. I modified the LD script to accommodate the new flash entry point FLASH (rx) : ORIGIN = 0x15000, LENGTH = 0x2b000 and RAM (rwx) : ORIGIN = 0x20002000, LENGTH = 0x2000. I am able to write the SD to the chip the I am not able to write my app. The error is :
*****\* Error: Failed to prepare for programming.
Failed to download RAMCode!

Thanks

**Comment by hlnd** [comment]
This is because S110 version 7.0.0 doesn't have a UICR section anymore, and so it needs to be flashed somewhat differently. Since 7.0.0 is still in alpha, I've pushed the needed changes, including an example Makefile for ble_app_hrs for PCA10001 in a branch, [support-for-s110-7.0.0-3-alpha](https://github.com/hlnd/nrf51-pure-gcc-setup/compare/support-for-s110-7.0.0-3-alpha) (c0f03cc).

If you use this branch instead of master, and make sure to point at the correct S110 headers, everything should work correctly.
